### ISSUE TITLE
prefab invisible to camera

### ISSUE THREAD

**Issue by willy1322** [julienkay/SNeRG-Unity-Viewer#1]
Hello im not a unity expert but he prefab is not showing on camera and play mode. i can see the item inside the mesh box but its not rendering. am i missing something ?

**Comment by julienkay** [comment]
Hi :)
What platform are you on? Windows?
Which scene does this happen with?

One thing to make sure of is, that the object needs to be at position (0, 0, 0)

**Comment by julienkay** [comment]
Oh, nevermind. I misunderstood. you're saying it doesn't work in Play Mode.
You'll have to change the 'Clear Flags' setting on the Main Camera from 'Skybox' to 'Solid Color' (ideally white) for it to show in Play Mode currently.

**Comment by willy1322** [comment]
![Image 2023-03-08 at 9 25 34 PM](https://user-images.githubusercontent.com/46135717/223824125-897374df-c656-4d82-9855-180a2d29c0cb.jpeg)
 windows, using 2021.3.3f1 build

**Comment by julienkay** [comment]
> You'll have to change the 'Clear Flags' setting on the Main Camera from 'Skybox' to 'Solid Color' (ideally white) for it to show in Play Mode currently.

For future versions I'll add 2 improvements:
- make sure it works with a camera using a skybox by default
- do proper depth testing to make sure it integrates with other opaque objects in the scene

**Comment by willy1322** [comment]
yes did that already working like a charm great port :) will pass it to the developers to play with :) cheers

**Comment by willy1322** [comment]
Sorry one last thing Julien , i was trying to play the project in vr (pcvr) using the xr interaction tool kit. It started rending in vr i could see the blue mesh cube like it was rendering then the reverythng disapeared and and red line showed on the floor nothing else. Now when i try to play in vr mode it dosen't show the mesh cube anymore, it just shows an 10m red line on the ground. Is there an issure rendinring in vr or the issure is from my side ? The pc i tried with has 32gb ram and 1080 8gb gpu, it still works normally on pc mode.

**Comment by julienkay** [comment]
The red line sounds like it might just be a pointer from the XR interaction toolkit. This happens often when controllers are not tracked or some of the interactions are not set up.

But you're right, the shader does not support stereo rendering yet. Adding that should be fairly straightforward, but I'm still fixing some of the rendering artifacts first before I add support for that. VR is definitely high on my priority list though!

**Comment by willy1322** [comment]
Ah great, so many use cases like projects show-casing in vr through the web browser it should work right on pcvr? which im already using with the Genesis depth package anyway but this is on another level :) Looking forward✌🏻

**Comment by julienkay** [comment]
Should mostly work fine with PCVR now. Let me know if you have any issues.

**Comment by willy1322** [comment]
yes confirmed wow the quality reflections and transparency. superb job. do u have any resources on how to create a dataset for a baking nerf? its hard find.

**Comment by julienkay** [comment]
I only have the information that's available in the official code release: https://github.com/google-research/google-research/tree/master/snerg
And I haven't had time to look into training my own datasets myself, so I'm not too much help there, unfortunately.

**Comment by willy1322** [comment]
ok will dive into that :)

**Comment by julienkay** [comment]
Closing this, but feel free to update in [discussions](https://github.com/julienkay/SNeRG-Unity-Viewer/discussions) or report back if you encounter any more issues.
