### ISSUE TITLE
How to add own snerg nerf？

### ISSUE THREAD

**Issue by schauberger** [julienkay/SNeRG-Unity-Viewer#2]
Could you tell how to train and add new snerg assets to project.

**Comment by julienkay** [comment]
For training your own dataset I would suggest starting with the instructions in the official repository:
https://github.com/google-research/google-research/tree/master/snerg

**Comment by schauberger** [comment]
After training how to convert and import model to the unity project？

**Comment by julienkay** [comment]
What do the output files look like?

I've just pushed some changes, that add another menu item 'Import from disk'.
It expects to be pointed to a folder that contains:
- a file named 'scene_params.json'
- a PNG file for the atlas texture: atlas_indices.png
- several PNG files for the feature texture: feature_XXX.png - feature_YYY.png
- several PNG files for the RGB and alpha texture: rgba_XXX.png - rgba_YYY.png

Let me know if there are any issues with it.

**Comment by schauberger** [comment]
Thanks for your great work！

**Comment by julienkay** [comment]
Did you manage to train a custom dataset and import it into Unity?

**Comment by schauberger** [comment]
Yep,I'm waiting for new GPUs to train custom dataset and import into Unity. It seems like that Mobile NeRF is more suitable for unbounded scene,but the requirement for GPU computing power is high.
And your twitter mentioned MERF as your future plan. So have you read this unofficial pytorch implementation of MeRF https://github.com/ashawkey/torch-merf？

**Comment by julienkay** [comment]
Cool, would love to see some results if you're able to share.
I haven't checked out that repo yet, but looks interesting. I'll keep you posted on how my progress with MERF is going, but I don't have anything to release yet.

**Comment by julienkay** [comment]
Closing this, but feel free to update in [discussions](https://github.com/julienkay/SNeRG-Unity-Viewer/discussions) or report any issues you're having.
