### ISSUE TITLE
Rendering Problem of  Real Captured Scene

### ISSUE THREAD

**Issue by 54way** [julienkay/SNeRG-Unity-Viewer#3]
Hi~
When I use the demo scene "sphares", the rendering result is like the image I post below.
If I made some mistake, could you help me to fix it?
or maybe it's some bug caused by pointing to wrong image atlas.
![image](https://github.com/julienkay/SNeRG-Unity-Viewer/assets/21360297/ad5e1c53-86d7-494d-b7b2-9028fe46b58a)

**Comment by julienkay** [comment]
Is this using the latest version of this project?

**Comment by 54way** [comment]
Yes, the is using the latest version of the project.
And I have already figured out what causes this issue.
The block grid size is wrong, and I've sent a pull request to fix it.
